### ISSUE TITLE
Add color indicators for grading status in lesson view

### ISSUE THREAD

**Issue by tomca32** [MindLeaps/tracker#728]
Tablet is using small colored stripes in front of student names to display if they have been graded in any skill, all of them, or none of them. Colors are yellow, green, and red respectively.

We should implement a similar system in the single lesson view.

![image](https://user-images.githubusercontent.com/3384784/68361093-87e05b00-00f0-11ea-9bf1-97841bdaf14d.png)

a quick hack shows this is possible with the following css
```css
td:before {
    content: '';
    width: 5px;
    height: 100%;
    background: red;
    position: absolute;
    left: 0;
}
```
